apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sample
  name: sample
spec:
  replicas: 10
  selector:
    matchLabels:
      app: sample
  strategy: {}
  template:
    metadata:
      labels:
        app: sample
    spec:
      containers:
      - name: php
        image: gwkim/php
        ports:
          - containerPort: 80
        imagePullPolicy: Never
        env:
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
